### ISSUE TITLE
Organizations

### ISSUE THREAD

**Issue by bradenrayhorn** [bradenrayhorn/switchboard-core#1]
Currently users on Switchboard can communicate with any other user on Switchboard. Organizations should be introduced to Switchboard to restrict communication to within that organization.

**Rules:**
- Organization can be created by any user
- A user cannot interact with Switchboard until they belong to at least one organization
  - A user will receive a prompt to create an organization or wait to be added to an organization.
- A user can belong to multiple organizations
- Users can invite other users to join existing organizations
  - An organization admin role will be added in the future
- Users and usernames are unique globally
- Channels/messages are independent on a per-organization basis
- Users may only view only organization at a time
  - Current organization can be switched via the top left dropdown in Switchboard

**Tasks:**

- [x] Add organization API to Core
- [x] Implement organization filtering on current Core endpoints
- [x] Add UI for new users to create an organization
